openapi: 3.0.3
info:
  title: FIAP_TC1
  version: 1.0.0
  description: API para gerenciar usuários (dono de restaurante e cliente)

servers:
  - url: http://localhost:8080/api/v1

tags:
  - name: users
    description: Operações relacionadas a usuários
  - name: auth
    description: Operações relacionadas a autenticação

paths:
  /auth/login:
    post:
      operationId: login
      tags:
        - auth
      summary: Autentica um usuário e retorna um token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: Usuário autenticado com sucesso
          content:
            application/json:
              schema:
                type: string
                example: eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ1c2VyQGV4YW1wbGUuY29tIiwiaWF0IjoxNjg5MjY4MDUwLCJleHAiOjE2ODkyNzA0NTB9.XxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXxXx
        '401':
          description: Credenciais inválidas
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users:
    get:
      operationId: getUsers
      tags:
        - users
      summary: Lista todos os usuários
      responses:
        '200':
          description: Lista de usuários retornada com sucesso (pode ser vazia)
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/UserResponse'

    post:
      operationId: createUser
      tags:
        - users
      summary: Cria um novo usuário
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '201':
          description: Usuário criado com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '400':
          description: Dados inválidos fornecidos
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/{id}:
    get:
      operationId: getUser
      tags:
        - users
      summary: Busca um usuário pelo ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Usuário encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Usuário não encontrado

    put:
      operationId: updateUser
      tags:
        - users
      summary: Atualiza um usuário existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/UserRequest'
      responses:
        '200':
          description: Usuário atualizado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserResponse'
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      operationId: deleteUser
      tags:
        - users
      summary: Deleta um usuário existente
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Usuário deletado com sucesso
        '404':
          description: Usuário não encontrado
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /users/change-password:
    put:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ChangePasswordRequest'
        required: true
      responses:
        '204':
          description: Senha trocada com sucesso.
      operationId: changePassword
      summary: Troca a senha do usuário.

components:
  schemas:
    ErrorResponse:
      type: object
      required:
        - message
        - code
        - status
        - path
      properties:
        message:
          type: string
          description: Mensagem de erro detalhada
        code:
          type: string
          description: Código do erro
        status:
          type: integer
          description: Código de status HTTP
        path:
          type: string
          description: URL da requisição
        fieldErrors:
          type: object
          description: Mapa de erros de validação específicos do campo.
          additionalProperties:
            type: string
    LoginRequest:
      type: object
      required:
        - login
        - password
      properties:
        login:
          type: string
          example: joaosilva123
        password:
          type: string
          format: password
          example: MyPassword123!
          description: Senha do usuário (não retornada nas consultas)
    UserRequest:
      type: object
      required:
        - name
        - email
        - login
        - password
        - address
        - role
      properties:
        name:
          type: string
          example: João Silva
          minLength: 3
          maxLength: 50
        email:
          type: string
          format: email
          example: joao@exemplo.com
        login:
          type: string
          example: joaosilva123
        password:
          type: string
          format: password
          example: MyPassword123!
          description: Senha do usuário (não retornada nas consultas)
        address:
          $ref: '#/components/schemas/Address'
        role:
          $ref: '#/components/schemas/UserRole'

    UserResponse:
      type: object
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: Identificador único (gerado automaticamente)
        name:
          type: string
          example: João Silva
        email:
          type: string
          format: email
          example: joao@exemplo.com
        login:
          type: string
          example: joaosilva123
        address:
          $ref: '#/components/schemas/Address'
        role:
          $ref: '#/components/schemas/UserRole'
        active:
          type: boolean
          example: true
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    Address:
      type: object
      required:
        - publicPlace
        - number
        - city
        - state
        - postalCode
      properties:
        id:
          type: string
          format: uuid
          readOnly: true
          description: Identificador único do endereço
        publicPlace:
          type: string
          example: Rua das Flores, 123
        number:
          type: string
          example: 123
        complement:
          type: string
          example: Apartamento 45
        neighborhood:
          type: string
          example: Centro
        city:
          type: string
          example: São Paulo
        state:
          type: string
          example: SP
        postalCode:
          type: string
          example: 01001-000
        country:
          type: string
          example: Brasil
        latitude:
          type: number
          format: double
          example: -23.55052
        longitude:
          type: number
          format: double
          example: -46.633308
        createdAt:
          type: string
          format: date-time
          readOnly: true
        updatedAt:
          type: string
          format: date-time
          readOnly: true

    ChangePasswordRequest:
      title: Root Type for ChangePassword
      description: ''
      type: object
      properties:
        idUser:
          type: string
          format: uuid
        newPassword:
          type: string
        confirmPassword:
          type: string
      example:
        idUser: 1
        lastPassword: Laf123
        newPassword: Laf1234

    UserRole:
      type: string
      description: Papel do usuário no sistema
      enum:
        - OWNER
        - CUSTOMER